name: 'Setup Hub'
description: 'Setup your Github Actions runner with Hub CLI'
author: 'Geert van der Cruijsen'
branding:
  icon: 'play'
  color: 'gray-dark'
inputs: - name: 
Setup Hub
  uses: 

hub-version:Geertvdc/setup-hub@v1.0.0
    description: 'Version of hub release, if not entered will use latest'
    required: false
runs:
  using: 'node12'
  main: 'lib/setup-hub.js'
